version: '3.8'

services:
  server:
    build: ./chitfunds_management_server
    container_name: chit-server-dev
    ports:
      - '5001:5001'
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    volumes:
      - ./chitfunds_management_server:/app
      - /app/__pycache__
    restart: unless-stopped
    command: python -m flask run --host=0.0.0.0 --port=5001

  client:
    build:
      context: ./chitfunds_management_client
      dockerfile: Dockerfile.dev
    container_name: chit-client-dev
    ports:
      - '5173:5173'
    volumes:
      - ./chitfunds_management_client:/app
      - /app/node_modules
    depends_on:
      - server
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:5001
