version: '3.8'

services:
  server:
    build: ./chitfunds_management_server
    container_name: chit-server
    ports:
      - '5001:5001'
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./chitfunds_management_server:/app
      - /app/__pycache__
    restart: unless-stopped

  client:
    build: ./chitfunds_management_client
    container_name: chit-client
    ports:
      - '3000:3000'
    depends_on:
      - server
    restart: unless-stopped
