version: "3.8"

services:
  backend:
    build:
      context: ./chitfunds_management_mysql_server
    restart: always
    working_dir: /app
    ports:
      - "5001:5001"
    command: python main.py


  frontend:
    build:
      context: ./chitfunds_management_client
    restart: always
    working_dir: /app
    ports:
      - "5173:80"  # or "3000:3000" if using create-react-app
    depends_on:
      - backend
    command: npm run dev


