version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: chitfunds_mysql
    restart: always
    environment:
      MYSQL_DATABASE: chitfunds
      MYSQL_ROOT_PASSWORD: chitfunds_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: chitfunds_app
    restart: always
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: chitfunds_password
      DB_NAME: chitfunds
      DB_PORT: 3306
    command: >
      bash -c "
        echo 'Waiting for MySQL to start...' &&
        sleep 10 &&
        python run.py
      "

volumes:
  mysql_data: 