"""make some changes in installments table

Revision ID: 0b672bb72218
Revises: cf9fe2bba442
Create Date: 2025-05-03 19:34:29.504415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b672bb72218'
down_revision: Union[str, None] = 'cf9fe2bba442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('installments', 'due_date',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Date(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('installments', 'due_date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
