"""in all models i have made some change like created_at

Revision ID: 0eb72bc29ab8
Revises: 223af1578d4d
Create Date: 2025-05-12 14:39:51.621996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0eb72bc29ab8'
down_revision: Union[str, None] = '223af1578d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chit_groups', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('chit_groups', 'created_by')
    op.add_column('chit_members', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('chit_members', 'created_by')
    op.add_column('installments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('installments', 'created_by')
    op.add_column('monthly_projections', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('monthly_projections', 'created_by')
    op.add_column('payment_installments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('payment_installments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('payments', 'created_by')
    op.drop_column('users', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by', mysql.DATETIME(), nullable=True))
    op.add_column('payments', sa.Column('created_by', mysql.DATETIME(), nullable=True))
    op.drop_column('payments', 'created_at')
    op.drop_column('payment_installments', 'updated_at')
    op.drop_column('payment_installments', 'created_at')
    op.add_column('monthly_projections', sa.Column('created_by', mysql.DATETIME(), nullable=True))
    op.drop_column('monthly_projections', 'created_at')
    op.add_column('installments', sa.Column('created_by', mysql.DATETIME(), nullable=True))
    op.drop_column('installments', 'created_at')
    op.add_column('chit_members', sa.Column('created_by', mysql.DATETIME(), nullable=True))
    op.drop_column('chit_members', 'created_at')
    op.add_column('chit_groups', sa.Column('created_by', mysql.DATETIME(), nullable=True))
    op.drop_column('chit_groups', 'created_at')
    # ### end Alembic commands ###
