"""added a new tables payment and payment_installment

Revision ID: b2aee21f3166
Revises: f50bce41bb08
Create Date: 2025-05-08 18:29:38.008995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2aee21f3166'
down_revision: Union[str, None] = 'f50bce41bb08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('payment_amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('net_paid_cash', sa.Float(), nullable=True),
    sa.Column('net_paid_online', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.Enum('CASH', 'PHONEPAY', 'GPAY', 'PAYTM', 'CHEQUE', 'OTHER', name='paymentmethodenum'), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', name='paymentstatusenum'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('payment_installments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('installment_id', sa.String(length=36), nullable=False),
    sa.Column('chit_member_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['chit_member_id'], ['chit_members.chit_member_id'], ),
    sa.ForeignKeyConstraint(['installment_id'], ['installments.installment_id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_installments')
    op.drop_table('payments')
    # ### end Alembic commands ###
