"""Initial tables

Revision ID: cf9fe2bba442
Revises: 
Create Date: 2025-05-03 17:19:43.711945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9fe2bba442'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chit_groups',
    sa.Column('chit_group_id', sa.String(length=36), nullable=False),
    sa.Column('chit_name', sa.String(length=255), nullable=False),
    sa.Column('chit_amount', sa.Float(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('total_members', sa.Integer(), nullable=False),
    sa.Column('monthly_installment', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('chit_group_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('aadhaar_number', sa.String(length=12), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'MANAGER', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('chit_members',
    sa.Column('chit_member_id', sa.String(length=36), nullable=False),
    sa.Column('chit_group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chit_group_id'], ['chit_groups.chit_group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('chit_member_id')
    )
    op.create_table('monthly_projections',
    sa.Column('monthly_projections_id', sa.String(length=36), nullable=False),
    sa.Column('chit_group_id', sa.String(length=36), nullable=False),
    sa.Column('month_number', sa.Integer(), nullable=False),
    sa.Column('monthly_subcription', sa.Float(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('total_payout', sa.Float(), nullable=False),
    sa.Column('lifted_date', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chit_group_id'], ['chit_groups.chit_group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('monthly_projections_id')
    )
    op.create_table('installments',
    sa.Column('installment_id', sa.String(length=36), nullable=False),
    sa.Column('chit_member_id', sa.String(length=36), nullable=False),
    sa.Column('month_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PAID', 'UNPAID', 'PARTIAL', name='paymentstatus'), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chit_member_id'], ['chit_members.chit_member_id'], ),
    sa.PrimaryKeyConstraint('installment_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('chit_member_id', sa.String(length=36), nullable=False),
    sa.Column('installment_id', sa.String(length=36), nullable=False),
    sa.Column('payment_amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('net_paid_cash', sa.Float(), nullable=True),
    sa.Column('net_paid_online', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.Enum('CASH', 'UPI', 'PHONEPAY', 'GPAY', 'OTHER', name='paymentmethodenum'), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', name='paymentstatusenum'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chit_member_id'], ['chit_members.chit_member_id'], ),
    sa.ForeignKeyConstraint(['installment_id'], ['installments.installment_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('installments')
    op.drop_table('monthly_projections')
    op.drop_table('chit_members')
    op.drop_table('users')
    op.drop_table('chit_groups')
    # ### end Alembic commands ###
