"""fix varchar length in projections_template

Revision ID: d9027114a581
Revises: e02c9ebf506b
Create Date: 2025-07-24 14:41:06.078457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9027114a581'
down_revision: Union[str, None] = 'e02c9ebf506b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projections_template',
    sa.Column('projectionTemplate_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('monthly_subscription', sa.Float(), nullable=False),
    sa.Column('months', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('projectionTemplate_id')
    )
    op.create_table('monthlyprojections_template',
    sa.Column('monthlyprojection_id', sa.String(length=36), nullable=False),
    sa.Column('projectionTemplate_id', sa.String(length=10), nullable=False),
    sa.Column('month_number', sa.Integer(), nullable=False),
    sa.Column('total_payout', sa.Float(), nullable=False),
    sa.Column('monthly_subscription', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projectionTemplate_id'], ['projections_template.projectionTemplate_id'], ),
    sa.PrimaryKeyConstraint('monthlyprojection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthlyprojections_template')
    op.drop_table('projections_template')
    # ### end Alembic commands ###
