"""Add token column to chit_members

Revision ID: e02c9ebf506b
Revises: 48490e1ef01f
Create Date: 2025-07-22 18:28:08.483717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e02c9ebf506b'
down_revision: Union[str, None] = '48490e1ef01f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chit_members', sa.Column('token', sa.Integer(), nullable=False))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('chit_members', 'token')
    # ### end Alembic commands ###
