"""your message here

Revision ID: eae5bf6ca72f
Revises: 0b672bb72218
Create Date: 2025-05-08 17:32:30.245180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eae5bf6ca72f'
down_revision: Union[str, None] = '0b672bb72218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('created_by', sa.DateTime(), nullable=True))
    op.drop_column('payments', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.drop_column('payments', 'created_by')
    # ### end Alembic commands ###
