"""made change in paymentmodel 

Revision ID: f50bce41bb08
Revises: 0581da786b57
Create Date: 2025-05-08 17:48:14.528136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f50bce41bb08'
down_revision: Union[str, None] = '0581da786b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'chit_member_id',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('payments', 'installment_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_foreign_key(None, 'payments', 'chit_members', ['chit_member_id'], ['chit_member_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.alter_column('payments', 'installment_id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('payments', 'chit_member_id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###
